### ISSUE TITLE
Can't Tag Characters

### ISSUE THREAD

**Issue by Mombie2020** [RolePlayGateway/roleplaygateway#218]
I don't have screenshots for this, however, I can tell you guys what is happening. When I type up my post and tag my characters, clicking send automatically logs me out of the site without the post both being made and the characters being tagged (obviously). I can, however, tag characters after posting through the "Tag Characters" function to the right of my post.

A number of people in the RPs I am in are discovering that they have the same issue with not being able to tag characters without being logged out of the site.

**Comment by martindale** [comment]
Related to #192.

**Comment by Lady-Awinita** [comment]
I think I know what is causing this issue as a whole. By superimposing the Explorer, and in a way, the old chat, into the site and over erverything {for example all characters in a place tagable, and the like} is causing the logout issue because most players generate their characters, and they appear in a random location. Then they use that cheracter in different locations instead of where they were generated.

As such, with the explorer it is possibel to move them yes. BUT, if they want to use the character in another location, {via tabbed posting} it causes the logout because the characters desired are not in that location. People are used to using this system of generating characters in random locales before posting them in other locales.

An example, I will use my first character, Vipteri for this example, she is currently in Wing City Gardens. If I were to post her say, in Masters Dojo, I would get logged out of the site on hitting POST because she is not phyiscally there in the Masters Dojo.

As such, the explorer, and the old chat, are linked. sadly so, and thusly the old chat continues to log me out when i try to use it. As of now, since yes it is still in beta, the explorer is linked to the old chat, and thusly, spreading it across the site, making it hard for users to make posts via tabs even in other universes not related to the Multiverse as Mombie has reported.

Therefore I sadly think, that by superimposing the explorer even as added features, is causing the constant logout issues.

However I could be entirely wrong as I havent yet been logged out since 18 hours ago as of this posting

NOTE: This is merely my personal interpretation of what is causingthe constant logging out issues, for all I know I am completely dead wrong

**Comment by lostamongtrees** [comment]
Is this an ongoing issue, @Lady-Awinita  @Mombie2020

**Comment by lostamongtrees** [comment]
cannot replicate, but tagging seems to present issues. closing for now
