### ISSUE TITLE
Character Sheet Contents Being Deleted

### ISSUE THREAD

**Issue by partially-stars** [RolePlayGateway/roleplaygateway#292]
When submitting a character sheet with contents that surpass a certain length, the contents of the sheet are deleted entirely and the sheet is submitted with no content. It’s happened in numerous universes and from multiple devices. Code in question is below.

```
[font=Garamond][hr][/hr][hr][/hr][color=#3a727f]███████████████████████████████████████████████████████████████████████[/color][hr][/hr][hr][/hr]
[center][img]circular%20or%20gif%20picture%20here.[/img]
[img]name%20from%201001%20or%20Fontmeme%20fonts.[/img]
[size=120][color=thought #3a727f]quote or something if you'd like[/color][color=transparent]x[/color][color=thought #3a727f] here[/color][/size][/font][/center]
[hr][/hr][hr][/hr][color=#3a727f]███████████████████████████████████████████████████████████████████████[/color][hr][/hr][hr][/hr][right][img]img%20or%20gif[/img] [img]img%20or%20gif[/img]
[img]img%20or%20gif[/img] [img]img%20or%20gif[/img][/right]
[font=Garamond][size=120][color=#3a727f][b]F U L L[/b][/color][color=transparent]X[/color][color=#3a727f][b]N A M E[/b][/color][/size]
Here

[size=120][color=#3a727f][b]N I C K N A M E (S)[/b][/color][/size]
Here

[size=120][color=#3a727f][b]B I R T H D A Y[/b][/color][/size]
Here

[size=120][color=#3a727f][b]A G E[/b][/color][/size]
Here

[size=120][color=#3a727f][b]P O S I T I O N[/b][/color][/size]
Here

[size=120][color=#3a727f][b]S E X U A L I T Y[/b][/color][/size]
Here

[size=120][color=#3a727f][b]E T H N I C I T Y[/b][/color][/size]
Here

[size=120][color=#3a727f][b]H O M E T O W N[/b][/color][/size]
Here

[size=120][color=#3a727f][b]H E X [/b][/color][/size]
Here[/font]
[hr][/hr][hr][/hr][color=#3a727f]███████████████████████████████████████████████████████████████████████[/color][hr][/hr][hr][/hr][font=Garamond][left][img]img%20or%20gif[/img]
[img]img%20or%20gif[/img]
[img]img%20or%20gif[/img][/left][size=120][color=#3a727f][b]P E R S O N A L I T Y[/b][/color][/size]
Here
[hr][/hr][hr][/hr][color=#3a727f]███████████████████████████████████████████████████████████████████████[/color][hr][/hr][hr][/hr]
[right][img]250x250[/img] [img]250x250[/img]
[img]250x250[/img] [img]250x250[/img]
[img]250x250[/img] [img]250x250[/img][/right]
[size=120][color=#3a727f][b]B L O O D[/b][/color][color=transparent]X[/color][color=#3a727f][b]S T A T U S[/b][/color][/size]
Here

[size=120][color=#3a727f][b]W A N D[/b][/color][/size]
Here

[size=120][color=#3a727f][b]P A T R O N U S[/b][/color][/size]
Here

[size=120][color=#3a727f][b]H O U S E[/b][/color][/size]
Here .

[size=120][color=#3a727f][b]B O G G A R T[/b][/color][/size]
Here

[size=120][color=#3a727f][b]F A M I L I A R[/b][/color][/size]
Here

[size=120][color=#3a727f][b]S P E C I A L I Z E S[/b][/color][color=transparent]X[/color][color=#3a727f][b]I N[/b][/color][/size]
Here.

[size=120][color=#3a727f][b]F A V O R I T E[/b][/color][color=transparent]X[/color][color=#3a727f][b]C L A S S[/b][/color][/size]
Here.

[size=120][color=#3a727f][b]T A L E N T S[/b][/color][/size]
Here

[size=120][color=#3a727f][b]S T R E N G T H S[/b][/color][/size]
here.

[size=120][color=#3a727f][b]W E A K N E S S E S[/b][/color][/size]
here
[hr][/hr][hr][/hr][color=#3a727f]███████████████████████████████████████████████████████████████████████[/color][hr][/hr][hr][/hr]
```

**Comment by martindale** [comment]
I've looked into this and found that a longer character profile (included below) seems to go through just fine; so this isn't an issue with the length of the profile.  Perhaps it has something to do with something within?  We'll have to test through process of elimination.

Original sample length (above) at 3,004 characters, sample below 5,034:
```
Break it down ipsum gangster sizzle for sure, dang adipiscing get down get down. Nullam sapien velizzle, tellivizzle volutpizzle, suscipit shut the shizzle up, vizzle, dawg. Pellentesque izzle tortor. Tellivizzle erizzle. Fizzle at dolor brizzle turpizzle tempizzle nizzle. Bling bling gangsta nibh tellivizzle turpis. Vestibulum izzle tortizzle. Pellentesque boofron rhoncizzle nisi. For sure pot i saw beyonces tizzles and my pizzle went crizzle platea dictumst. Pot bow wow wow. Dang tellus break it down, pretizzle eu, that's the shizzle black, izzle vitae, nunc. Sizzle suscipizzle. Integer sempizzle velit funky fresh fo shizzle my nizzle.

Vivamizzle shizzlin dizzle mauris eget nisi sheezy pretizzle. Vivamus sizzle amet dope. Nam eu nisl mammasay mammasa mamma oo sa izzle auctor shizzlin dizzle. Shit suscipit doggy fizzle. Curabitizzle shiz arcu. Own yo' enizzle enizzle, auctizzle stuff, sure eu, dignissim doggy, fizzle. Izzle yo pede for sure eros things mammasay mammasa mamma oo sa. Quisque pede black, pulvinizzle, daahng dawg pot, mollis sizzle amizzle, erizzle. Stuff izzle dui. Aliquam shiz purus, doggy consectetizzle, sollicitudin in, consequat imperdiet, brizzle. Quisque a dang eu mi gizzle shit. Curabitur accumsizzle sagittis ipsizzle. Get down get down habitant morbi tristique bling bling izzle fo shizzle et malesuada fames izzle turpizzle you son of a bizzle. In fo shizzle. Curabitizzle tellivizzle. Ut da bomb felis, ass quis, phat izzle, boom shackalack pulvinizzle, doggy. Shizznit sagittis yippiyo fo shizzle.

Donizzle break yo neck, yall auctizzle mauris. Phasellizzle dope elizzle izzle nibh pretizzle dope. Maecenas a pimpin'. Vestibulum in lacizzle maurizzle bow wow wow boofron. Rizzle izzle tortor sizzle dang erizzle ultrices porta. In away tortor, ultricizzle mofo, hendrerit crunk, adipiscing ass, sure. Etiam velizzle leo, aliquam consequat, dang ass, dictizzle check it out, turpis. Vivamizzle neque. I saw beyonces tizzles and my pizzle went crizzle lorem. Bow wow wow pizzle ma nizzle dawg libero commodo bow wow wow. Fusce hizzle crazy eu nibh things mah nizzle. Phasellizzle fermentum sapien nizzle shiz. Suspendisse lorem bizzle, sollicitudizzle sizzle, fo shizzle my nizzle own yo', shizznit nec, justo. Donizzle faucibizzle porttitor stuff. Pizzle feugizzle, tellus black ornare tempizzle, sapizzle stuff tincidunt shiz, egizzle dapibus pede funky fresh my shizz fo shizzle mah nizzle fo rizzle, mah home g-dizzle. Phasellizzle fo shizzle fo, i saw beyonces tizzles and my pizzle went crizzle izzle, tempus stuff, sempizzle owned, sapizzle. Ut gizzle ass fo shizzle for sure. Shiz ante nibh, suscipizzle funky fresh, vestibulizzle et, rutrizzle check it out, velizzle. Mauris mammasay mammasa mamma oo sa mauris. Sizzle fo magna shit amet risus iaculizzle dizzle.

In gravida away nec est. Shit pot. We gonna chung tempizzle. Donizzle izzle mi a eros its fo rizzle things. Dizzle hizzle ipsizzle. Sed hizzle est check it out gangster. I'm in the shizzle a ipsum vitae urna ghetto ullamcorpizzle. Crunk nizzle cool. Vivamizzle bling bling lacizzle fo shizzle felis. Morbi eget justo. Etizzle shit dui izzle magna sizzle away. Morbi placerat, non euismizzle porta, nisl est mofo nunc, boom shackalack ornare break it down gangster brizzle amizzle est. Morbi dawg. Vestibulum fo break yo neck, yall yo mamma sheezy ma nizzle orci luctus izzle go to hizzle away phat Phat; Vestibulum vehicula, dizzle laorizzle rizzle mammasay mammasa mamma oo sa, phat lorizzle its fo rizzle nunc, a break yo neck, yall urna metus break yo neck, yall nibh. Duis pretium erizzle at nulla. Phasellizzle accumsizzle. Cizzle socizzle natoque ghetto et magnizzle cool parturient montes, fo shizzle mah nizzle fo rizzle, mah home g-dizzle fizzle check it out. Prizzle izzle massa yo quizzle ultrices dope. Donec nizzle fo.

Nunc break yo neck, yall erizzle ut urna. Bizzle congue. Vestibulum viverra bizzle dui. sizzle izzle boofron own yo' cool dang condimentizzle. Own yo' potenti. Its fo rizzle izzle sizzle vitae purizzle tincidunt aliquizzle. Sheezy tempizzle ante. In interdum erat izzle sizzle. Crazy fizzle. vitae dizzle sizzle diam mollizzle fo shizzle. Nulla bow wow wow. Nullizzle break yo neck, yall yo mamma a massa ghetto pulvinar. Nullizzle sagittis bizzle da bomb brizzle. Crizzle yo mamma bow wow wow izzle tellus. Fo shizzle pretizzle purizzle non dui. Get down get down shiznit purizzle.

Fo shizzle mah nizzle fo rizzle, mah home g-dizzle stuff ligula. Crazy porta ass nizzle. Sure viverra, rizzle the bizzle shizzlin dizzle hendrerizzle, libero urna shizzlin dizzle leo, crackalackin condimentum my shizz sapizzle at nunc. Donizzle da bomb dolizzle. Vestibulizzle mah nizzle felizzle. Sed doggy check it out erizzle. Integer nulla gizzle, izzle fo shizzle my nizzle, volutpizzle boofron, auctizzle fo shizzle, nunc. Sed pharetra. Daahng dawg nisi. Curabitizzle sit amizzle leo nec ante crazy you son of a bizzle. Quisque laorizzle tellivizzle sizzle amet enizzle. Cool tempizzle black felizzle.
```

**Comment by kohananinja** [comment]
Here is the code I am having issues with: 

[font=Garamond][hr][/hr][hr][/hr][color=#ad1100]███████████████████████████████████████████████████████████████████████[/color][hr][/hr][hr][/hr]
[center][img]https://i.imgur.com/Tjrm5AQ.gif[/img]
[img]https://i.imgur.com/w8gZZ4t.png[/img]
[size=120][color=#ad1100]quote or something if you'd like[/color][color=transparent]x[/color][color=thought #ad1100] here[/color][/size][/font][/center]
[hr][/hr][hr][/hr][color=#ad1100]███████████████████████████████████████████████████████████████████████[/color][hr][/hr][hr][/hr][right][img]img%20or%20gif[/img] [img]img%20or%20gif[/img]
[img]img%20or%20gif[/img] [img]img%20or%20gif[/img][/right]
[font=Garamond][size=120][color=#ad1100][b]F U L L[/b][/color][color=transparent]X[/color][color=#ad1100][b]N A M E[/b][/color][/size]
Coalatian Abernathy

[size=120][color=#ad1100][b]N I C K N A M E (S)[/b][/color][/size]
Coal

[size=120][color=#ad1100][b]B I R T H D A Y[/b][/color][/size]
February, 23rd

[size=120][color=#ad1100][b]A G E[/b][/color][/size]
 17

[size=120][color=#ad1100][b]Y E A R[/b][/color][/size]
7th

[size=120][color=#ad1100][b]S E X U A L I T Y[/b][/color][/size]
Bisexual

[size=120][color=#ad1100][b]E T H N I C I T Y[/b][/color][/size]
Caucasian, British

[size=120][color=#ad1100][b]H O M E T O W N[/b][/color][/size]
London, England

[size=120][color=#ad1100][b]H E X [/b][/color][/size]
#ad1100[/font]
[hr][/hr][hr][/hr][color=#ad1100]███████████████████████████████████████████████████████████████████████[/color][hr][/hr][hr][/hr][font=Garamond][left][img]img%20or%20gif%20500x500[/img][/left]

[img]img%20or%20gif[/img]
[img]img%20or%20gif[/img][/left][size=120][color=#ad1100][b]P E R S O N A L I T Y[/b][/color][/size]
 Coal is something of a care free soul, or at least that is the persona he likes to project to the rest of the world. He’s exceptionally laid back, never seems to take anything too seriously, and his eyes sparkle with a devil-may-care flare that has drawn many a girl and boy (sometime at the same time) to his bed. He’s always down for a good prank, and frequently acts as a soundboard for some of Mac’s more elaborate schemes. As often as Coal finds himself in trouble though, he’s as skilled at getting himself out, with a silver tongue and dimpled smile that has a habit of melting hearts. He never seems to get mad, always flowing like water with the flow of things, adapting quickly to a situation as it changes with an affable ease that many envy. His reputation as a charmer has made him popular to an extent, but he maintains a very tight, closed circle of friends that he rarely allows himself to expand. To those within it, he is a fierce friend, and loyal confidant, though his own troubles are usually kept close to the vest. Coal can also be incredibly stubborn at times, despite his best efforts to try and just shrug and let things go. Once Coal digs in his heels on something, decision made, he is immovable.

Underneath that candy, good time boy, coating Coal often puts on to face the world though, is a bone deep weariness that threatens to swallow him whole into the depths of darkest depression. His young life has been shaped by violence, defined by the knowledge that he [i]isn’t[/i] the chosen one of anything. He’s seen darkness and knows truths he’s powerless to even speak aloud, and that sense of helplessness has taken its toll. In the family, Coal is the spare, a problematic left over tied to memories best left secret, his only real value the pure blood flowing through his veins. Coal’s home life is...complicated. He doesn’t like to talk about it, and is usually part of the pack who stays at Hogwarts during breaks, only venturing off Hogwarts’ protected grounds when forced to in the summers. Few people are really privy to the reasoning behind this choice, and his best friend Harvey is the only one who truly knows most of the details. Coal trusts him to keep it that way.

[hr][/hr][hr][/hr][color=#ad1100]███████████████████████████████████████████████████████████████████████[/color][hr][/hr][hr][/hr]
[img]img%20or%20gif[/img]
[img]img%20or%20gif[/img][/left]
[size=120][color=#ad1100][b]H I S T O R Y[/b][/color][/size]
The House of Abernathy has always been a proud and prestigious one, boasting exceptionalism and achievements beyond counting among the members of its family. They also are, and have always been, unrepentant blood supremacists. The family is everything to the Abernathys, it’s purity and prosperity of paramount importance. Anyone who threatens that is dealt with harshly, and mercy is not a word many in the family know. Everyone serves a purpose, and those who cease to be useful often find their home within Amesley Manor an uncomfortable one. Coal has never been useful, more often he is viewed as a problematic inconvenience.

A large family with many branches, Coal’s father became useful to the family for one reason; his gift of retrocognition. With a mere touch and the right focus, he could see the history, and more importantly the origins of the objects he touched, learning the secrets to the lost spells or rituals that created the dark objects the family had gotten their hands on over the centuries. That kind of power always has a price though, and the repeated over use of it to dive in and view some of the darkest rituals known to wizard kind exacted a terrible toll on Luthor Abernathy’s mind. It drove him mad, and one night in a fit of mania, he attacked his wife and child, killing Coal’s mother. The “incident” as it was forever referred to after, was largely covered up. Luthor was shut off to a privately owned facility, his mental state further deteriorating, and it was made clear early on to Coal that speaking of it to anyone would have frightening consequences. Especially his cousin Orion.

The two were purposely kept apart until they both began attending Hogwarts the same year. To the dismay of many, both boys were sorted into the same house, so additional measures were taken to keep them apart. Growing up, Coal had very little interaction with his cousin the family seemed to prize so highly, but Coal is perceptive, and he saw the road to the slaughterhouse being laid out for Orion. His cousin had the same gift his father had, and he knew what would happen if they used him in the same way. So during Christmas holiday their 4th year, Coal made a decision. He kept his head down, played the cowed boy they wanted him to be, and bided his time in search of an opening to get Orion alone, and warn him. It almost worked too, but Bartholomew Abernathy is perceptive too.

There are few wizards who frighten Coal more than his grandfather, and with good reason as there are few who can match the man for his efficient use of cruelty, and his mastery of the dark arts. When he caught Coal in the act, the punishment was swift and severe, idle threats were never issued. He started with the Cruciatus curse, that was for Coal’s disloyalty, a necessary rebuke. The burn mark he left was a visible reminder that it could happen again, whenever he liked, but the final stroke was the worst. To ensure Coal never tried to speak the truth to Orion again, Bartholomew cast a rare and grim curse known by rumor alone as ‘Silence the Witness’. Should Coal impart the knowledge he knows in any way, betraying the head of his house, the curse will trigger and a slow gruesome death will follow.  Coal has not been back to Amesley Manor since that day he was allowed to crawl out of the basement, usually opting to stay at Hogwarts during the Holiday breaks, or stay with the Gibsons during the summer. Harvey was there at the train station when Coal was at his lowest, saw the marks that would fade in time, and the despair on his friend’s face he couldn’t yet shove behind the mask. He [i]knows[/i] Coal’s family is responsible, but Harvey’s never been able to get Coal to talk about it after that day.

[hr][/hr][hr][/hr][color=#ad1100]███████████████████████████████████████████████████████████████████████[/color][hr][/hr][hr][/hr]
[right][img]250x250[/img] [img]250x250[/img]
[img]250x250[/img] [img]250x250[/img]
[img]250x250[/img] [img]250x250[/img][/right]
[size=120][color=#ad1100][b]B L O O D[/b][/color][color=transparent]X[/color][color=#ad1100][b]S T A T U S[/b][/color][/size]
Pure Blood

[size=120][color=#ad1100][b]W A N D[/b][/color][/size]
Willow, Unicorn Hair, 13 ¾”, Firm

[size=120][color=#ad1100][b]P A T R O N U S[/b][/color][/size]
Dolphin

[size=120][color=#ad1100][b]H O U S E[/b][/color][/size]
Gryffindor

[size=120][color=#ad1100][b]B O G G A R T[/b][/color][/size]
His Grandfather

[size=120][color=#ad1100][b]F A M I L I A R[/b][/color][/size]
A ginger cat named Carver

[size=120][color=#ad1100][b]S P E C I A L I Z E S[/b][/color][color=transparent]X[/color][color=#ad1100][b]I N[/b][/color][/size]
Non-Verbal Magic, Potions

[size=120][color=#ad1100][b]F A V O R I T E[/b][/color][color=transparent]X[/color][color=#ad1100][b]C L A S S[/b][/color][/size]
Defense Against the Dark Arts, Potions

[size=120][color=#ad1100][b]T A L E N T S[/b][/color][/size]
[b]Quidditch:[/b] Coal is naturally athletic, and plays as one of the main chasers for the Gryffindor Quidditch Team

[b]Perceptive:[/b] Coal has always been an observant kid. Growing up he had to be. It makes him pretty good at reading a room, situation, or other people, but he’s not infallible.

[b]Charm:[/b] Coal has an easy way with people. He’s good at saying the right thing, putting people at ease, and all around smoothing out the ruffles of an uncomfortable situation with a smile, a light joke, and his patent brand of Coal warmth. People tend to like him, or at least feel safe around him for the most part.

[hr][/hr][hr][/hr][color=#ad1100]███████████████████████████████████████████████████████████████████████[/color][hr][/hr][hr][/hr]

**Comment by thaumatology** [comment]
is this still an issue?
