### ISSUE TITLE
Locations accessible via the descend direction do not appear in the list of neighboring places in The Multiverse

### ISSUE THREAD

**Issue by LawOfTheLand** [RolePlayGateway/roleplaygateway#65]
Some places avoid this problem by having the main spaceport be down from the planet, but in each case of ascension, the previous place was invisible in the list of neighbors. This held true for repeated uses of the ascend command as well, from "Terra" to "New Terra: High Orbit" to "Sol" to "Sol: Deep Space" to "AH-302".

**Comment by LawOfTheLand** [comment]
Update: Descent locations are sometimes visible in the place list, but the direction is not listed. Example:

Game Master (GM)
You have arrived at Sol. Owner: Remæus
A lonely yellow orbited by a small number of habitable planets, Sol is unremarkable.

Visible exits: Sol: Deep Space [ascend]
Characters here: Nikki Oceantide, Jaydenn Mera, Aion Farlaeris, Reian, Paro Temaru, Samantha Anne James, Shinklaire, duke thorson, Almira Mahala, Ellis Avery, Penguin, Frank Cethin, Avi Deomanti, ADAM:00, john bishop, Toronto Ontario Cananda, Tabitha (Shadow), Spine Industries and Security, Daigo Yutani, The Devil's Businessman
Also: Terra, New Terra: High Orbit, Sol: Deep Space, The Haven, SOL-Stat

Sol is ascendant from Terra, but the reverse is not so listed. `/descend Terra` works normally from here, however.

**Comment by thaumatology** [comment]
Found something: In order for the `/descend ` command to work, you must include the location name to which you are descending. Descendable locations are also not appearing as descendable locations . Here are some screenshots that reveal the process in which this was figured out.

```
/join Gaia
/look
/descend
/destroy descend
/build descend crystal nexus
```
![screen shot 2017-08-28 at 4 18 09 pm](https://user-images.githubusercontent.com/31420084/29792027-18c4e074-8c0d-11e7-9fb1-c7dbfea3dcad.png)

There was no response from the GM upon attempting to build, so I tried a second consecutive time, only to be told something already exists in that direction. However, when you go to `/descend`, you are told there's nowhere to descend to. `/look` also does not include any descendable locations, though it is included in the list of locations "in" 
![screen shot 2017-08-28 at 4 18 37 pm](https://user-images.githubusercontent.com/31420084/29792029-18c5dfb0-8c0d-11e7-9cb6-dd0152b339b7.png)

So, we destroyed the exit again, and rebuilt it again. Notice how the destruction prompts a response from GM, but upon building the exit, there is no reaction.
`/build descend crystal nexus`
Resulted in GM telling me some place already exists in that direction, for a second time.
`/descend` resulted in going nowhere
![screen shot 2017-08-28 at 4 18 49 pm](https://user-images.githubusercontent.com/31420084/29792028-18c5908c-8c0d-11e7-8e08-d721b4891112.png)

Saw mention of the command `/descend Terra` being used

 `/descend Crystal Nexus`
`/look`
![screen shot 2017-08-28 at 4 19 07 pm](https://user-images.githubusercontent.com/31420084/29792030-18c831c0-8c0d-11e7-9548-a3f07bc134b9.png)

Arrived! 

_Conclusion_: You must include the room name to which you are descending (`/descend Terra` , `/descend Crystal Nexus` , etc)  in order for the command to work, otherwise it won't work. `/ascend` seems to work just fine. This may have something to do with the `/look` complication

**Comment by martindale** [comment]
We changed how the 5th dimension functions; while they still operate like normal exits, they now reflect parent/child relationships (containers) between locations.  We still need to update several commands to reflect this, including `/build`.

**Comment by lostamongtrees** [comment]
Thank you @LawOfTheLand !
